#!/bin/bash
set -euo pipefail

swift --version

swift package dollup --allow-writing-to-package-directory
git diff --exit-code

swift build -c release \
    --explicit-target-dependency-import-check=error \
    --build-tests

swift test -c release \
    --skip-build \
    --explicit-target-dependency-import-check=error

# clean up after the test
rm -r Sources/SystemTests/directories/new
